using KeplerTalento.Domain.Candidates;
using KeplerTalento.Domain.Documents;

namespace KeplerTalento.Application.Abstractions.Persistence;

public enum CandidateSaveOutcome
{
    Saved,
    ConcurrencyConflict,

    /// <summary>
    /// A database constraint refused the write — an unknown status, a second primary
    /// document, or a relation naming a catalog entry of the wrong family. The slice
    /// translates it into a stable validation code; the detail never reaches the caller.
    /// </summary>
    ConstraintViolation,
}

/// <summary>
/// What the list screen shows for one candidate. Deliberately not the aggregate: the
/// list renders core fields only, and joining six collections per row for a list nobody
/// expands would be waste.
/// </summary>
public sealed record CandidateSummary(
    Guid Id,
    string FirstName,
    string LastName,
    string Phone,
    string Email,
    string Location,
    string Province,
    string Country,
    string Availability,
    string Status,
    string Source,
    string Notes,
    DateOnly? ReceivedAt,
    DateOnly? ConsentAt,
    DateOnly? ReviewDueAt,
    bool IsActive,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    uint Version,
    /// <summary>
    /// How many documents the candidate has. A count, not a collection: the list screen
    /// shows whether a CV exists and filters on it, and answering that with a number
    /// keeps the list query from fanning out into the collections it deliberately omits.
    /// </summary>
    int DocumentCount,
    /// <summary>
    /// The candidate's principal CV, or null. An identifier, not personal data — it is
    /// what lets the list and the search results offer "Abrir CV" without loading the
    /// document collection.
    /// </summary>
    Guid? PrimaryDocumentId);

// Persistence-only compatibility shape for the KTL-7 migration implementation. No
// application command or HTTP route accepts it after KTL-9; documents are created only
// by the content-carrying upload slice.
public sealed record DocumentMetadata(
    Guid? Id,
    string DocumentType,
    string OriginalFilename,
    string MimeType,
    long SizeBytes,
    bool IsPrimary);

/// <summary>
/// One document's metadata as a write supplies it. There is no storage key and no scan
/// state: until KTL-9 moves the bytes, a document record is metadata and nothing else, and
/// the storage key is the persistence layer's business either way.
/// </summary>
/// <summary>
/// The candidate aggregate's persistence contract, modelled on
/// <see cref="ICatalogRepository"/>. There is deliberately no delete member: a candidate
/// is removed logically, by <see cref="Candidate.Deactivate"/>, and the runtime database
/// role holds no <c>DELETE</c> on the candidate tables either.
/// </summary>
public interface ICandidateRepository
{
    /// <summary>
    /// Loads one candidate with every collection it owns. A logically removed candidate
    /// is returned as readily as an active one: removal is logical, and the detail screen
    /// renders a removed candidate with a restore action.
    /// </summary>
    Task<Candidate?> FindAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>Loads a candidate without its collections, for writes that do not touch them.</summary>
    Task<Candidate?> FindCoreAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>Excludes logically removed candidates unless <paramref name="includeInactive"/>.</summary>
    Task<IReadOnlyList<CandidateSummary>> ListAsync(bool includeInactive, CancellationToken cancellationToken);

    Task<IReadOnlyList<CandidateDocument>> ListDocumentsAsync(Guid candidateId, CancellationToken cancellationToken);

    void Add(Candidate candidate);

    /// <summary>
    /// Registers a relation record as an insert.
    /// </summary>
    /// <remarks>
    /// Relation identifiers are generated by the application, not the store, so a new
    /// record reaches the change tracker with its key already set. Discovered only through
    /// the aggregate's navigation, that is indistinguishable from an existing row, and EF
    /// would issue an UPDATE that matches nothing. Saying "this is new" explicitly is the
    /// only version of this that cannot be got wrong.
    /// </remarks>
    void AddRelation(CandidateRelation relation);

    /// <summary>
    /// Deletes relation records that left a replaced collection. This is the one physical
    /// deletion in the aggregate, and it is of a relation the user removed — never of a
    /// candidate.
    /// </summary>
    void RemoveRelations(IEnumerable<CandidateRelation> relations);

    /// <summary>
    /// Replaces a candidate's document metadata as a whole set, against its version, and
    /// records one audit event.
    /// </summary>
    /// <remarks>
    /// This is a repository member rather than something the slice assembles because the
    /// order of the writes matters and only the persistence layer can control it: "at most
    /// one primary document per candidate" is a non-deferrable partial unique index, so
    /// clearing the old primary flag must reach the database before the new one is set.
    /// Both phases and the audit event share one transaction.
    /// </remarks>
    /// <summary>
    /// Declares the version the caller read, so a write against a stale version is
    /// rejected rather than silently overwriting a concurrent change.
    /// </summary>
    void ExpectVersion(Candidate candidate, uint version);

    /// <summary>
    /// Persists the pending changes together with one audit event, in a single
    /// transaction, so a rejected change can never leave an applied-change event behind.
    /// </summary>
    Task<CandidateSaveOutcome> SaveAsync(string auditEventType, string subjectId, CancellationToken cancellationToken);
}
