FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine
WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.d/40-envsubst.sh /docker-entrypoint.d/40-envsubst.sh
COPY --from=build /app/dist/ ./
COPY public/env.template.js ./env.template.js
USER root
RUN chmod +x /docker-entrypoint.d/40-envsubst.sh && chown -R nginx:nginx /usr/share/nginx/html
USER nginx
EXPOSE 8080
