// <auto-generated />
using System;
using KeplerTalento.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260826064607_ExpandCandidateSchema")]
    partial class ExpandCandidateSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeplerTalento.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("AUD_Events", (string)null);
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("ConsentAt")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("ReceivedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReviewDueAt")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("SourceLoadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_Candidates_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("IsActive", "UpdatedAtUtc")
                        .HasDatabaseName("IX_CND_Candidates_IsActive_UpdatedAtUtc");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("CND_Candidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_Candidates_Deleted", "(\"IsActive\" AND \"DeletedAtUtc\" IS NULL) OR (NOT \"IsActive\" AND \"DeletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CND_Candidates_Name", "char_length(\"FirstName\") > 0 AND char_length(\"LastName\") > 0");

                            t.HasCheckConstraint("CK_CND_Candidates_SourceLoaded", "\"SourceLoadedAtUtc\" IS NULL OR \"SourceKey\" IS NOT NULL");

                            t.HasCheckConstraint("CK_CND_Candidates_Status", "\"Status\" IN ('new', 'available', 'in_process', 'hired', 'rejected')");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EducationTypeFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("EducationTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateEducation_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateEducation_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("EducationTypeId", "EducationTypeFamily");

                    b.HasIndex("StatusId", "StatusFamily");

                    b.ToTable("CND_CandidateEducation", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateEducation_Degree", "char_length(\"Degree\") > 0 AND char_length(\"Institution\") > 0");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_EducationTypeFamily", "\"EducationTypeFamily\" = 'education_type'");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_EndYear", "\"EndYear\" IS NULL OR (\"EndYear\" BETWEEN 1900 AND 2200)");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_StatusFamily", "\"StatusFamily\" = 'education_status'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Functions")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SectorFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateExperience_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateExperience_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("SectorId", "SectorFamily");

                    b.ToTable("CND_CandidateExperience", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateExperience_Company", "char_length(\"Company\") > 0 AND char_length(\"Position\") > 0");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_Period", "(\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\") AND (NOT \"IsCurrent\" OR \"EndDate\" IS NULL)");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_SectorFamily", "\"SectorFamily\" = 'sector'");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_YearsExperience", "\"YearsExperience\" IS NULL OR \"YearsExperience\" >= 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Certification")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LanguageFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateLanguages_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateLanguages_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("LanguageId", "LanguageFamily");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.ToTable("CND_CandidateLanguages", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateLanguages_LanguageFamily", "\"LanguageFamily\" = 'language'");

                            t.HasCheckConstraint("CK_CND_CandidateLanguages_LevelFamily", "\"LevelFamily\" = 'language_level'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProgramFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidatePrograms_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidatePrograms_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.HasIndex("ProgramId", "ProgramFamily");

                    b.ToTable("CND_CandidatePrograms", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidatePrograms_LevelFamily", "\"LevelFamily\" = 'program_level'");

                            t.HasCheckConstraint("CK_CND_CandidatePrograms_ProgramFamily", "\"ProgramFamily\" = 'program'");

                            t.HasCheckConstraint("CK_CND_CandidatePrograms_YearsExperience", "\"YearsExperience\" IS NULL OR \"YearsExperience\" >= 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SkillFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateSkills_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateSkills_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.HasIndex("SkillId", "SkillFamily");

                    b.ToTable("CND_CandidateSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateSkills_LevelFamily", "\"LevelFamily\" = 'skill_level'");

                            t.HasCheckConstraint("CK_CND_CandidateSkills_SkillFamily", "\"SkillFamily\" = 'skill'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Catalogs.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "Family")
                        .HasName("AK_CAT_CatalogItems_Id_Family");

                    b.HasIndex("Family", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CAT_CatalogItems_Family_Code");

                    b.HasIndex("Family", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_CAT_CatalogItems_Family_NameNormalized");

                    b.HasIndex("Family", "SortOrder");

                    b.ToTable("CAT_CatalogItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CAT_CatalogItems_Family", "\"Family\" IN ('language', 'program', 'skill', 'language_level', 'program_level', 'skill_level', 'education_type', 'education_status', 'sector')");

                            t.HasCheckConstraint("CK_CAT_CatalogItems_Name", "char_length(\"NameEs\") > 0 AND char_length(\"NameNormalized\") > 0 AND char_length(\"Code\") > 0");

                            t.HasCheckConstraint("CK_CAT_CatalogItems_SortOrder", "\"SortOrder\" > 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Documents.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ScanFailureCode")
                        .HasColumnType("text");

                    b.Property<string>("ScanState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannerSignature")
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_Documents_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex(new[] { "CandidateId" }, "IX_CND_Documents_CandidateId");

                    b.HasIndex(new[] { "CandidateId" }, "UX_CND_Documents_CandidateId_Primary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\"");

                    b.ToTable("CND_Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_Documents_Size", "\"Size\" > 0 AND \"Size\" <= 20971520");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Operations.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAtUtc");

                    b.ToTable("OPS_Operations", null, t =>
                        {
                            t.HasCheckConstraint("CK_OPS_Operations_Attempts", "\"AttemptCount\" >= 0 AND \"MaxAttempts\" > 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateEducation", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("EducationTypeId", "EducationTypeFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("StatusId", "StatusFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateExperience", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("SectorId", "SectorFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateLanguage", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LanguageId", "LanguageFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateProgram", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ProgramId", "ProgramFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateSkill", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("SkillId", "SkillFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Documents.CandidateDocument", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
