// <auto-generated />
using System;
using KeplerTalento.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeplerTalento.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_AUD_Events_CreatedAtUtc");

                    b.HasIndex("ActorUserId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AUD_Events_ActorUserId_CreatedAtUtc");

                    b.HasIndex("EventType", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AUD_Events_EventType_CreatedAtUtc");

                    b.HasIndex("SubjectId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AUD_Events_SubjectId_CreatedAtUtc");

                    b.ToTable("AUD_Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_AUD_Events_Actor", "(\"ActorKind\" IS NULL AND \"ActorUserId\" IS NULL) OR (\"ActorKind\" = 'system' AND \"ActorUserId\" IS NULL) OR (\"ActorKind\" = 'user' AND \"ActorUserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("ConsentAt")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("ReceivedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReviewDueAt")
                        .HasColumnType("date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("SourceLoadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_Candidates_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("IsActive", "UpdatedAtUtc")
                        .HasDatabaseName("IX_CND_Candidates_IsActive_UpdatedAtUtc");

                    b.HasIndex("LastName", "FirstName");

                    b.HasIndex("IsActive", "Status", "Id")
                        .HasDatabaseName("IX_CND_Candidates_IsActive_Status_Id");

                    b.HasIndex("IsActive", "LastName", "FirstName", "Id")
                        .HasDatabaseName("IX_CND_Candidates_IsActive_LastName_FirstName_Id");

                    b.ToTable("CND_Candidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_Candidates_Deleted", "(\"IsActive\" AND \"DeletedAtUtc\" IS NULL) OR (NOT \"IsActive\" AND \"DeletedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CND_Candidates_Name", "char_length(\"FirstName\") > 0 AND char_length(\"LastName\") > 0");

                            t.HasCheckConstraint("CK_CND_Candidates_SourceLoaded", "\"SourceLoadedAtUtc\" IS NULL OR \"SourceKey\" IS NOT NULL");

                            t.HasCheckConstraint("CK_CND_Candidates_Status", "\"Status\" IN ('new', 'available', 'in_process', 'hired', 'rejected')");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateEducation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EducationTypeFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("EducationTypeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StatusFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateEducation_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateEducation_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("EducationTypeId", "EducationTypeFamily");

                    b.HasIndex("StatusId", "StatusFamily");

                    b.ToTable("CND_CandidateEducation", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateEducation_Degree", "char_length(\"Degree\") > 0 AND char_length(\"Institution\") > 0");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_EducationTypeFamily", "\"EducationTypeFamily\" = 'education_type'");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_EndYear", "\"EndYear\" IS NULL OR (\"EndYear\" BETWEEN 1900 AND 2200)");

                            t.HasCheckConstraint("CK_CND_CandidateEducation_StatusFamily", "\"StatusFamily\" = 'education_status'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Functions")
                        .HasColumnType("text");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SectorFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateExperience_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateExperience_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("SectorId", "SectorFamily");

                    b.ToTable("CND_CandidateExperience", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateExperience_Company", "char_length(\"Company\") > 0 AND char_length(\"Position\") > 0");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_Period", "(\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\") AND (NOT \"IsCurrent\" OR \"EndDate\" IS NULL)");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_SectorFamily", "\"SectorFamily\" = 'sector'");

                            t.HasCheckConstraint("CK_CND_CandidateExperience_YearsExperience", "\"YearsExperience\" IS NULL OR \"YearsExperience\" >= 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Certification")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LanguageFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateLanguages_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateLanguages_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("CandidateId", "LanguageId")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateLanguages_CandidateId_LanguageId");

                    b.HasIndex("LanguageId", "LanguageFamily");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.ToTable("CND_CandidateLanguages", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateLanguages_LanguageFamily", "\"LanguageFamily\" = 'language'");

                            t.HasCheckConstraint("CK_CND_CandidateLanguages_LevelFamily", "\"LevelFamily\" = 'language_level'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProgramFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidatePrograms_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidatePrograms_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("CandidateId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidatePrograms_CandidateId_ProgramId");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.HasIndex("ProgramId", "ProgramFamily");

                    b.ToTable("CND_CandidatePrograms", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidatePrograms_LevelFamily", "\"LevelFamily\" = 'program_level'");

                            t.HasCheckConstraint("CK_CND_CandidatePrograms_ProgramFamily", "\"ProgramFamily\" = 'program'");

                            t.HasCheckConstraint("CK_CND_CandidatePrograms_YearsExperience", "\"YearsExperience\" IS NULL OR \"YearsExperience\" >= 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("LevelFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SkillFamily")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_CND_CandidateSkills_CandidateId");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateSkills_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("CandidateId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_CandidateSkills_CandidateId_SkillId");

                    b.HasIndex("LevelId", "LevelFamily");

                    b.HasIndex("SkillId", "SkillFamily");

                    b.ToTable("CND_CandidateSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_CandidateSkills_LevelFamily", "\"LevelFamily\" = 'skill_level'");

                            t.HasCheckConstraint("CK_CND_CandidateSkills_SkillFamily", "\"SkillFamily\" = 'skill'");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Catalogs.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "Family")
                        .HasName("AK_CAT_CatalogItems_Id_Family");

                    b.HasIndex("Family", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CAT_CatalogItems_Family_Code");

                    b.HasIndex("Family", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("UX_CAT_CatalogItems_Family_NameNormalized");

                    b.HasIndex("Family", "SortOrder");

                    b.ToTable("CAT_CatalogItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CAT_CatalogItems_Family", "\"Family\" IN ('language', 'program', 'skill', 'language_level', 'program_level', 'skill_level', 'education_type', 'education_status', 'sector')");

                            t.HasCheckConstraint("CK_CAT_CatalogItems_Name", "char_length(\"NameEs\") > 0 AND char_length(\"NameNormalized\") > 0 AND char_length(\"Code\") > 0");

                            t.HasCheckConstraint("CK_CAT_CatalogItems_SortOrder", "\"SortOrder\" > 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Documents.CandidateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ScanFailureCode")
                        .HasColumnType("text");

                    b.Property<string>("ScanState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScannerSignature")
                        .HasColumnType("text");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CND_Documents_SourceKey")
                        .HasFilter("\"SourceKey\" IS NOT NULL");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex(new[] { "CandidateId" }, "IX_CND_Documents_CandidateId");

                    b.HasIndex(new[] { "CandidateId" }, "UX_CND_Documents_CandidateId_Primary")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\"");

                    b.ToTable("CND_Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_CND_Documents_Size", "\"Size\" > 0 AND \"Size\" <= 20971520");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Permissions");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_Roles_Name");

                    b.ToTable("ADM_Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_ADM_Roles_Label", "char_length(btrim(\"Label\")) > 0");

                            t.HasCheckConstraint("CK_ADM_Roles_Name", "\"Name\" ~ '^[a-z0-9_]+$'");

                            t.HasCheckConstraint("CK_ADM_Roles_Permissions", "jsonb_typeof(\"Permissions\") = 'array' AND jsonb_array_length(\"Permissions\") > 0");

                            t.HasCheckConstraint("CK_ADM_Roles_Timestamps", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_Users_Email");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_Users_ExternalSubject")
                        .HasFilter("\"ExternalSubject\" IS NOT NULL");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("IX_ADM_Users_RoleName");

                    b.ToTable("ADM_Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_ADM_Users_DisplayName", "char_length(btrim(\"DisplayName\")) > 0");

                            t.HasCheckConstraint("CK_ADM_Users_Email", "\"Email\" = lower(\"Email\") AND position('@' in \"Email\") > 1");

                            t.HasCheckConstraint("CK_ADM_Users_ExternalSubject", "\"ExternalSubject\" IS NULL OR char_length(btrim(\"ExternalSubject\")) > 0");

                            t.HasCheckConstraint("CK_ADM_Users_Timestamps", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\" AND (\"LastSignInAtUtc\" IS NULL OR \"LastSignInAtUtc\" >= \"CreatedAtUtc\")");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Import.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorExternalKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FilePurgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoadedRows")
                        .HasColumnType("integer");

                    b.Property<int>("OperationAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RejectedRows")
                        .HasColumnType("integer");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SkippedRows")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UnresolvedValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("UnresolvedValues");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ValidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("IX_ADM_ImportBatches_Sha256");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_ImportBatches_StorageKey");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending()
                        .HasDatabaseName("IX_ADM_ImportBatches_CreatedAtUtc_Id");

                    b.HasIndex("State", "ClosedAtUtc")
                        .HasDatabaseName("IX_ADM_ImportBatches_State_ClosedAtUtc");

                    b.ToTable("ADM_ImportBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_ADM_ImportBatches_Counts", "\"LoadedRows\" >= 0 AND \"RejectedRows\" >= 0 AND \"SkippedRows\" >= 0 AND \"OperationAttempt\" >= 0 AND (\"RowCount\" IS NULL AND \"LoadedRows\" + \"RejectedRows\" + \"SkippedRows\" = 0 OR \"RowCount\" >= 0 AND \"LoadedRows\" + \"RejectedRows\" + \"SkippedRows\" = \"RowCount\")");

                            t.HasCheckConstraint("CK_ADM_ImportBatches_Purge", "(\"State\" <> 'expired' OR \"FilePurgedAtUtc\" IS NOT NULL) AND (\"FilePurgedAtUtc\" IS NULL OR \"State\" IN ('expired', 'infected', 'unscannable'))");

                            t.HasCheckConstraint("CK_ADM_ImportBatches_Sha256", "\"Sha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_ADM_ImportBatches_SizeBytes", "\"SizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ADM_ImportBatches_State", "\"State\" IN ('uploaded', 'scanning', 'scanned', 'validating', 'validated', 'committing', 'committed', 'infected', 'unscannable', 'failed', 'expired')");

                            t.HasCheckConstraint("CK_ADM_ImportBatches_Timestamps", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\"");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Import.ImportRowOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId")
                        .HasDatabaseName("IX_ADM_ImportRowOutcomes_CandidateId")
                        .HasFilter("\"CandidateId\" IS NOT NULL");

                    b.HasIndex("BatchId", "RowNumber")
                        .HasDatabaseName("IX_ADM_ImportRowOutcomes_BatchId_RowNumber");

                    b.HasIndex("BatchId", "Phase", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_ImportRowOutcomes_BatchId_Phase_RowNumber");

                    b.ToTable("ADM_ImportRowOutcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ADM_ImportRowOutcomes_Candidate", "\"CandidateId\" IS NULL OR (\"Outcome\" = 'loaded' AND \"Phase\" = 'commit')");

                            t.HasCheckConstraint("CK_ADM_ImportRowOutcomes_Outcome", "\"Outcome\" IN ('loaded', 'rejected', 'skipped')");

                            t.HasCheckConstraint("CK_ADM_ImportRowOutcomes_Phase", "\"Phase\" IN ('validation', 'commit')");

                            t.HasCheckConstraint("CK_ADM_ImportRowOutcomes_ReasonCode", "(\"ReasonCode\" IS NULL OR \"ReasonCode\" IN ('field.required', 'field.too_long', 'email.invalid', 'date.invalid', 'status.unknown', 'reference.malformed', 'reference.unresolved', 'reference.duplicate', 'row.shape_invalid', 'candidate.refused', 'candidate.duplicate')) AND (\"Outcome\" = 'loaded' OR \"ReasonCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ADM_ImportRowOutcomes_RowNumber", "\"RowNumber\" >= 1");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Operations.MigrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackupLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DocumentsLoaded")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentsRejected")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoadedRows")
                        .HasColumnType("integer");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RejectedRows")
                        .HasColumnType("integer");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text");

                    b.Property<int>("SkippedRows")
                        .HasColumnType("integer");

                    b.Property<int>("SourceRows")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnmatchedTargetRecords")
                        .HasColumnType("integer");

                    b.Property<int>("UnresolvedValues")
                        .HasColumnType("integer");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("IX_OPS_MigrationRuns_StartedAtUtc");

                    b.ToTable("OPS_MigrationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_OPS_MigrationRuns_BackupLabel", "\"Verb\" <> 'load' OR \"BackupLabel\" IS NOT NULL");

                            t.HasCheckConstraint("CK_OPS_MigrationRuns_Outcome", "\"Outcome\" IN ('running', 'reconciled', 'not_reconciled', 'failed')");

                            t.HasCheckConstraint("CK_OPS_MigrationRuns_Verb", "\"Verb\" IN ('validate', 'load', 'report')");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Operations.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAtUtc");

                    b.ToTable("OPS_Operations", null, t =>
                        {
                            t.HasCheckConstraint("CK_OPS_Operations_Attempts", "\"AttemptCount\" >= 0 AND \"MaxAttempts\" > 0");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Search.SearchPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilterSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UX_ADM_SearchPresets_NormalizedName");

                    b.ToTable("ADM_SearchPresets", null, t =>
                        {
                            t.HasCheckConstraint("CK_ADM_SearchPresets_FilterSchemaVersion", "\"FilterSchemaVersion\" >= 1");

                            t.HasCheckConstraint("CK_ADM_SearchPresets_Filters", "jsonb_typeof(\"Filters\") = 'object'");

                            t.HasCheckConstraint("CK_ADM_SearchPresets_Name", "char_length(btrim(\"Name\")) > 0 AND char_length(\"NormalizedName\") > 0");

                            t.HasCheckConstraint("CK_ADM_SearchPresets_Timestamps", "\"UpdatedAtUtc\" >= \"CreatedAtUtc\" AND (\"LastUsedAtUtc\" IS NULL OR \"LastUsedAtUtc\" >= \"CreatedAtUtc\")");

                            t.HasCheckConstraint("CK_ADM_SearchPresets_Version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateEducation", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany("Education")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("EducationTypeId", "EducationTypeFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("StatusId", "StatusFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateExperience", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany("Experience")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("SectorId", "SectorFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateLanguage", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany("Languages")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LanguageId", "LanguageFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateProgram", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany("Programs")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("ProgramId", "ProgramFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.CandidateSkill", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany("Skills")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("LevelId", "LevelFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("SkillId", "SkillFamily")
                        .HasPrincipalKey("Id", "Family")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Documents.CandidateDocument", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Identity.User", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeplerTalento.Domain.Import.ImportBatch", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KeplerTalento.Domain.Import.ImportRowOutcome", b =>
                {
                    b.HasOne("KeplerTalento.Domain.Import.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeplerTalento.Domain.Candidates.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KeplerTalento.Domain.Candidates.Candidate", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Languages");

                    b.Navigation("Programs");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
